CREATE TABLE IF NOT EXISTS insurance_policies(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    number INTEGER NOT NULL,
    insurance_company VARCHAR(50),
    expiration_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS medical_cards (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    number INTEGER NOT NULL,
    date_of_issue DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS passports (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    series VARCHAR(50) NOT NULL,
    number VARCHAR(13) NOT NULL
);

CREATE TABLE IF NOT EXISTS pacients (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    FIO VARCHAR(50) NOT NULL,
    passport_id INTEGER NOT NULL REFERENCES passports(id) ON DELETE CASCADE ON UPDATE CASCADE,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(10) NOT NULL,
    adress VARCHAR(100) NOT NULL,
    place_of_work VARCHAR(50),
    number_phone VARCHAR(12) NOT NULL,
    email VARCHAR(30),
    insurance_policy_id INTEGER NOT NULL REFERENCES insurance_policies(id) ON DELETE CASCADE ON UPDATE CASCADE,
    medical_card_id INTEGER NOT NULL REFERENCES medical_cards(id) ON DELETE CASCADE ON UPDATE CASCADE,
    date_last_appeal DATE,
    date_next_appeal DATE
);

CREATE TABLE IF NOT EXISTS doctors (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    FIO VARCHAR(50) NOT NULL,
    specialization VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS types_events(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS medical_events(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    date DATETIME NOT NULL,
    pacient_id INTEGER NOT NULL REFERENCES pacients(id) ON DELETE CASCADE ON UPDATE CASCADE,
    doctor_id INTEGER NOT NULL REFERENCES doctors(id) ON DELETE CASCADE ON UPDATE CASCADE,
    type_event_id INTEGER NOT NULL REFERENCES types_events(id) ON DELETE CASCADE ON UPDATE CASCADE,
    name VARCHAR(50) NOT NULL, 
    result VARCHAR(50) NOT NULL
);

CREATE TABLE users 
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50),
    password VARCHAR(50)
);  